Adding a emulator
microsoft/jbpf pull request #4
Opened 2024-10-28 10:08 UTC by doctorlai-msrc

This PR adds the emulator at `src/emulator` and integrate it in the CMake, please refer to `src/emulator/README.md` for more details.

2025-05-25 22:27 UTC, xfoukas requested changes

2025-05-25 22:27 UTC, xfoukas commented on src/emulator/README.md
> +#include "jbpf_gnb_flexran_l1_hooks.h"
This header file does not exist anywhere in the codebase and shouldn't be referenced.

2025-05-25 22:27 UTC, xfoukas commented on src/emulator/README.md
> +#include "nr5g_mac_phy_api.h"
This header file does not exist anywhere in the codebase and shouldn't be referenced.

2025-05-25 22:27 UTC, xfoukas commented on src/emulator/README.md
> +JBPF Emulator provides a testing framework to test the codelets using the Python script. Here is how it works:
This readme requires a better and more detailed explanation of what this emulator is about. 
It should cover the following in more details:
1. Why do we need an emulator? Why did we choose python?
2. What is the high level idea of how the emulator works? How does it link to this codebase and to the codebases of developers?
3. The capabilities of the emulator should be listed and described (e.g., the capability to emulate time events, capture outputs, etc.).
4. What does it mean it needs to be build once per project (what is a project in this context)?

Also, this readme file should be accompanied by a concrete example that guides the user, similar to the examples we provide for the basic jbpf functionality.

2025-05-25 22:27 UTC, xfoukas commented on src/emulator/README.md
> +## Build dummy emulator
What is a dummy emulator useful for? Do we even need instructions for this? If so, we should describe what is the use case. Otherwise, we should only focus on the example with the custom hooks and completely skip the dummy part.

2025-05-25 22:27 UTC, xfoukas commented on src/emulator/README.md
> +When JBPF is build statically with `-DJBPF_STATIC=1`, the emulator will be built with the `libjbpf.a` library. Otherwise, the emulator will be built with the `libjbpf.so` library.
Is this relevant to the user?

2025-05-25 22:27 UTC, xfoukas commented on src/emulator/README.md
> +DEFINE_HOOK_AND_WRAPPER(fapi_gnb_dl_csirs_pdu, tCsiRsPduStruct, "y#iiiiii", int, carrier_idx, cell_id, sfn, slot, nSym)
This should be explained in more details. It does not use the hook macro API of jbpf and as such it is not obvious to a user what it is and why/how it should be used.

2025-05-25 22:27 UTC, xfoukas commented on src/emulator/README.md
> +### Convert C structs to Python
Which C structs is this referring to?

2025-05-25 22:27 UTC, xfoukas commented on src/emulator/README.md
> +ctypesgen -a ../lcm/jbpf_lcm_api.h --no-macro-warnings -I ../io -I ../mem_mgmt -I ../common -o $OUTPUT_DIR/lib/jbpf_lcm_api.py
Is this actually needed or is it just a generic example of how to convert a C header file to python? If it is the latter, then I think it would be more helpful to have a conversion for an actual example here instead.

2025-05-25 22:27 UTC, xfoukas commented on src/emulator/README.md
> +## patch jbpf_lcm_api.py to add _pack_=1
What is this needed for? Why does he user need to do that and if they need to do it always, can we not provide a way to hide these extra steps from the user?

2025-05-25 22:27 UTC, xfoukas commented on src/emulator/README.md
> +You can add custom helper functions such as xran decoder to the `$JBPF_PATH/out/emulator/test/helper_functions.hpp`
xran decoder is not something that many people using this codebase will be familiar with. We need an actual working example.

2025-05-25 22:27 UTC, xfoukas commented on src/emulator/README.md
> +If the Cmake option `JBPF_STATIC` is set to `1`, the emulator will link to `$JBPF_OUT_DIR/out/lib/libjbpf.a`, otherwise, it will require `$JBPF_OUT_DIR/out/lib/libjbpf.so`
Is this relevant information to the user? If so, we should explain why.

2025-05-25 22:27 UTC, xfoukas commented on src/emulator/README.md
> +## Example Tests
If those examples explain all of the above steps, then we should provide documentation discussing those examples.

2025-05-25 22:27 UTC, xfoukas commented on src/emulator/autogen-hook-wrappers.py
> +        hooks = regex.findall(rf'{hook}\((.*?)\)', data, regex.DOTALL)
I believe this can be done with the built-in `re` module.

2025-05-25 22:27 UTC, xfoukas commented on src/emulator/autogen-hook-wrappers.py
> +## this script reads the C header files and then generate the wrapper functions for Jbpf Emulator
Typo: `generates`.

2025-05-25 22:27 UTC, xfoukas commented on helper_build_files/build_jbpf_lib.sh
> +    ## As the emulator tests are not built with the same flags as the rest of the project, they may trigger ODR violations
Why are the emulator tests not built with the same flags?

2025-05-25 22:27 UTC, xfoukas commented on src/emulator/test/test_time_event.py
> +for i in range(TOTAL_TIME_EVENTS):
This functionality is not referenced anywhere in the documentation.

2025-05-25 22:27 UTC, xfoukas commented on src/emulator/test/test_time_event.py
> +import os, sys, ctypes
A description about this test should be added at the top, same as the rest of the jbpf tests.

2025-05-25 22:27 UTC, xfoukas commented on src/emulator/test/test_report_stats.py
> +import os, sys, ctypes
A description of the test should be added on top, same as the rest of the jbpf tests.

2025-05-25 22:27 UTC, xfoukas commented on src/emulator/test/test_periodic_call.py
> +import os, sys, ctypes
A description of the test should be added on top, same as the rest of the jbpf tests.

2025-05-25 22:27 UTC, xfoukas commented on src/emulator/test/test_2.py
> +import os, sys, time, ctypes
A description of the test should be added on top, same as the rest of the jbpf tests.

2025-05-25 22:27 UTC, xfoukas commented on src/emulator/test/test_1.py
> +import os, sys, time, ctypes
A description of the test should be added on top, same as the rest of the jbpf tests.

2025-05-25 22:27 UTC, xfoukas commented on src/emulator/test/test_0.py
> +import os, sys, time, ctypes
A description of the test should be added on top, same as the rest of the jbpf tests.

2025-05-25 22:27 UTC, xfoukas commented on src/emulator/emulator.cpp
> +#include "test/hooks.h"
Why does the main emulator include files that are under `test`? This structure doesn't seem right to me.

2025-06-18 13:34 UTC, doctorlai-msrc commented on src/emulator/CMakeLists_emulator.txt
> +project(jbpf_emulator)
This file gets copied to the out/emulator where other projects e.g. FlexRAN can build a custom emulator with custom hooks and helper functions. So this file is for building emulator on project basis.

2025-06-18 13:35 UTC, doctorlai-msrc commented on src/emulator/test/hooks.h
> +
Yes, this is the place to put custom hooks.

2025-07-02 10:05 UTC, merged